# Generated by Django 4.2 on 2023-04-27 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='Date and time of Order creation')),
                ('is_fulfilled', models.BooleanField(default=False, help_text='Is Order finished and client got his products', verbose_name='Fulfilled')),
                ('is_paid', models.BooleanField(default=False, help_text='Is Order has been paid', verbose_name='Paid')),
                ('is_takeaway', models.BooleanField(help_text='Is Order been taken as a takeaway', verbose_name='Takeaway')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.SmallIntegerField(help_text='Amount of product ordered')),
                ('price_per_unit', models.SmallIntegerField(help_text='Price per one unit', verbose_name='Price Per Unit')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='orders.OrderItem', to='products.product'),
        ),
    ]
